#!/usr/bin/env python3
import os,sys

cmake_root = os.path.abspath(os.path.dirname(os.path.realpath(__file__)))
python_path = os.path.join(cmake_root,"BuildTools","Python")
sys.path.append(python_path)

from ild import get_depend,building,generate_mk_file

ancona_target = "Android"

if ancona_target == "Android":
    if not building.is_android_ndk_installed():
        print("Error: Failed to build ancona for Android")
        sys.exit(1)
    get_depend.main(cmake_root,"Android")
    building.generate_ancona_build(cmake_root,"Android")
