#pragma once

#include <Ancona/Core2D/InputDevices/InputHandler.hpp>
#include <Ancona/Core2D/Systems/Audio/AutoStartMusicSystem.hpp>
#include <Ancona/Core2D/Systems/Audio/Music.hpp>
#include <Ancona/Core2D/Systems/Audio/MusicSystem.hpp>
#include <Ancona/Core2D/Systems/Audio/Sound.hpp>
#include <Ancona/Core2D/Systems/Audio/SoundSystem.hpp>
#include <Ancona/Core2D/Systems/CameraSystem.hpp>
#include <Ancona/Core2D/Systems/Collision/Collision.hpp>
#include <Ancona/Core2D/Systems/Collision/CollisionComponent.hpp>
#include <Ancona/Core2D/Systems/Collision/CollisionSystem.hpp>
#include <Ancona/Core2D/Systems/Drawable/AnimatedDrawable.hpp>
#include <Ancona/Core2D/Systems/Drawable/ContainerDrawable.hpp>
#include <Ancona/Core2D/Systems/Drawable/Drawable.hpp>
#include <Ancona/Core2D/Systems/Drawable/DrawableComponent.hpp>
#include <Ancona/Core2D/Systems/Drawable/DrawableSystem.hpp>
#include <Ancona/Core2D/Systems/Drawable/FadeDrawableSystem.hpp>
#include <Ancona/Core2D/Systems/Drawable/ImageDrawable.hpp>
#include <Ancona/Core2D/Systems/Drawable/ShapeDrawable.hpp>
#include <Ancona/Core2D/Systems/Drawable/TextDrawable.hpp>
#include <Ancona/Core2D/Systems/Drawable/TileBlockDrawable.hpp>
#include <Ancona/Core2D/Systems/InputControlComponent.hpp>
#include <Ancona/Core2D/Systems/InputControlSystem.hpp>
#include <Ancona/Core2D/Systems/PathFollowerSystem.hpp>
#include <Ancona/Core2D/Systems/PathSystem.hpp>
#include <Ancona/Core2D/Systems/PositionSystem.hpp>
#include <Ancona/Core2D/Systems/RotateSystem.hpp>
#include <Ancona/Core2D/Systems/TriggerDeathSystem.hpp>
