#pragma once

#include <Ancona/Framework/Audio/Jukebox.hpp>
#include <Ancona/Framework/Audio/JukeboxSounds.hpp>
#include <Ancona/Framework/Config/Config.hpp>
#include <Ancona/Framework/EntityFramework/AbstractSystem.hpp>
#include <Ancona/Framework/EntityFramework/Entity.hpp>
#include <Ancona/Framework/EntityFramework/SystemManager.hpp>
#include <Ancona/Framework/EntityFramework/UnorderedSystem.hpp>
#include <Ancona/Framework/EntityFramework/UpdateStep.hpp>
#include <Ancona/Framework/Resource/AbstractLoader.hpp>
#include <Ancona/Framework/Resource/FontLoader.hpp>
#include <Ancona/Framework/Resource/HalResourceLoader.hpp>
#include <Ancona/Framework/Resource/RequestList.hpp>
#include <Ancona/Framework/Resource/ResourceLibrary.hpp>
#include <Ancona/Framework/Resource/ResourceLoaderInit.hpp>
#include <Ancona/Framework/Resource/SoundBufferLoader.hpp>
#include <Ancona/Framework/Resource/TextureLoader.hpp>
#include <Ancona/Framework/Screens/AbstractScreen.hpp>
#include <Ancona/Framework/Screens/LoadingScreen.hpp>
#include <Ancona/Framework/Screens/ScreenManager.hpp>
#include <Ancona/Framework/Serializing/Archive.hpp>
#include <Ancona/Framework/Serializing/ClassConstructor.hpp>
#include <Ancona/Framework/Serializing/HalSerializer.hpp>
#include <Ancona/Framework/Serializing/MapSerializer.hpp>
#include <Ancona/Framework/Serializing/PolymorphicMap.hpp>
#include <Ancona/Framework/Serializing/PolymorphicRegistration.hpp>
#include <Ancona/Framework/Serializing/PolymorphicSerializer.hpp>
#include <Ancona/Framework/Serializing/Serializer.hpp>
#include <Ancona/Framework/Serializing/Serializing.hpp>
#include <Ancona/Framework/Serializing/SerializingContext.hpp>
#include <Ancona/Framework/Serializing/StdSerializer.hpp>
#include <Ancona/Framework/Serializing/UtilSerializer.hpp>
#include <Ancona/Framework/Systems/ScreenSystemsContainer.hpp>
