#pragma once

#include <Ancona/HAL/BlendMode.hpp>
#include <Ancona/HAL/CircleShape.hpp>
#include <Ancona/HAL/Clock.hpp>
#include <Ancona/HAL/Drawable.hpp>
#include <Ancona/HAL/Event.hpp>
#include <Ancona/HAL/Font.hpp>
#include <Ancona/HAL/Joystick.hpp>
#include <Ancona/HAL/Keyboard.hpp>
#include <Ancona/HAL/Mouse.hpp>
#include <Ancona/HAL/Music.hpp>
#include <Ancona/HAL/PrimitiveRenderType.hpp>
#include <Ancona/HAL/RectangleShape.hpp>
#include <Ancona/HAL/RenderStates.hpp>
#include <Ancona/HAL/RenderTarget.hpp>
#include <Ancona/HAL/RenderTexture.hpp>
#include <Ancona/HAL/Sensor.hpp>
#include <Ancona/HAL/Shape.hpp>
#include <Ancona/HAL/Sleep.hpp>
#include <Ancona/HAL/Sound.hpp>
#include <Ancona/HAL/SoundBuffer.hpp>
#include <Ancona/HAL/SoundSource.hpp>
#include <Ancona/HAL/Sprite.hpp>
#include <Ancona/HAL/Text.hpp>
#include <Ancona/HAL/Texture.hpp>
#include <Ancona/HAL/Time.hpp>
#include <Ancona/HAL/Touch.hpp>
#include <Ancona/HAL/Vertex.hpp>
#include <Ancona/HAL/VertexArray.hpp>
#include <Ancona/HAL/Window.hpp>

#include <Ancona/HAL/SFML.hpp>
